//
//  Categories.swift
//  Yelp
//
//  Created by Oscar Bonilla on 9/21/17.
//  Copyright © 2017 Timothy Lee. All rights reserved.
//

import Foundation

struct Category {
    var name: String
    var code: String
}

let Categories: [Category] = [
    Category(name: "Afghan", code: "afghani"),
    Category(name: "African", code: "african"),
    Category(name: "American, New", code: "newamerican"),
    Category(name: "American, Traditional", code: "tradamerican"),
    Category(name: "Arabian", code: "arabian"),
    Category(name: "Argentine", code: "argentine"),
    Category(name: "Armenian", code: "armenian"),
    Category(name: "Asian Fusion", code: "asianfusion"),
    Category(name: "Asturian", code: "asturian"),
    Category(name: "Australian", code: "australian"),
    Category(name: "Austrian", code: "austrian"),
    Category(name: "Baguettes", code: "baguettes"),
    Category(name: "Bangladeshi", code: "bangladeshi"),
    Category(name: "Barbeque", code: "bbq"),
    Category(name: "Basque", code: "basque"),
    Category(name: "Bavarian", code: "bavarian"),
    Category(name: "Beer Garden", code: "beergarden"),
    Category(name: "Beer Hall", code: "beerhall"),
    Category(name: "Beisl", code: "beisl"),
    Category(name: "Belgian", code: "belgian"),
    Category(name: "Bistros", code: "bistros"),
    Category(name: "Black Sea", code: "blacksea"),
    Category(name: "Brasseries", code: "brasseries"),
    Category(name: "Brazilian", code: "brazilian"),
    Category(name: "Breakfast & Brunch", code: "breakfast_brunch"),
    Category(name: "British", code: "british"),
    Category(name: "Buffets", code: "buffets"),
    Category(name: "Bulgarian", code: "bulgarian"),
    Category(name: "Burgers", code: "burgers"),
    Category(name: "Burmese", code: "burmese"),
    Category(name: "Cafes", code: "cafes"),
    Category(name: "Cafeteria", code: "cafeteria"),
    Category(name: "Cajun/Creole", code: "cajun"),
    Category(name: "Cambodian", code: "cambodian"),
    Category(name: "Canadian", code: "New)"),
    Category(name: "Canteen", code: "canteen"),
    Category(name: "Caribbean", code: "caribbean"),
    Category(name: "Catalan", code: "catalan"),
    Category(name: "Chech", code: "chech"),
    Category(name: "Cheesesteaks", code: "cheesesteaks"),
    Category(name: "Chicken Shop", code: "chickenshop"),
    Category(name: "Chicken Wings", code: "chicken_wings"),
    Category(name: "Chilean", code: "chilean"),
    Category(name: "Chinese", code: "chinese"),
    Category(name: "Comfort Food", code: "comfortfood"),
    Category(name: "Corsican", code: "corsican"),
    Category(name: "Creperies", code: "creperies"),
    Category(name: "Cuban", code: "cuban"),
    Category(name: "Curry Sausage", code: "currysausage"),
    Category(name: "Cypriot", code: "cypriot"),
    Category(name: "Czech", code: "czech"),
    Category(name: "Czech/Slovakian", code: "czechslovakian"),
    Category(name: "Danish", code: "danish"),
    Category(name: "Delis", code: "delis"),
    Category(name: "Diners", code: "diners"),
    Category(name: "Dumplings", code: "dumplings"),
    Category(name: "Eastern European", code: "eastern_european"),
    Category(name: "Ethiopian", code: "ethiopian"),
    Category(name: "Fast Food", code: "hotdogs"),
    Category(name: "Filipino", code: "filipino"),
    Category(name: "Fish & Chips", code: "fishnchips"),
    Category(name: "Fondue", code: "fondue"),
    Category(name: "Food Court", code: "food_court"),
    Category(name: "Food Stands", code: "foodstands"),
    Category(name: "French", code: "french"),
    Category(name: "French Southwest", code: "sud_ouest"),
    Category(name: "Galician", code: "galician"),
    Category(name: "Gastropubs", code: "gastropubs"),
    Category(name: "Georgian", code: "georgian"),
    Category(name: "German", code: "german"),
    Category(name: "Giblets", code: "giblets"),
    Category(name: "Gluten-Free", code: "gluten_free"),
    Category(name: "Greek", code: "greek"),
    Category(name: "Halal", code: "halal"),
    Category(name: "Hawaiian", code: "hawaiian"),
    Category(name: "Heuriger", code: "heuriger"),
    Category(name: "Himalayan/Nepalese", code: "himalayan"),
    Category(name: "Hong Kong Style Cafe", code: "hkcafe"),
    Category(name: "Hot Dogs", code: "hotdog"),
    Category(name: "Hot Pot", code: "hotpot"),
    Category(name: "Hungarian", code: "hungarian"),
    Category(name: "Iberian", code: "iberian"),
    Category(name: "Indian", code: "indpak"),
    Category(name: "Indonesian", code: "indonesian"),
    Category(name: "International", code: "international"),
    Category(name: "Irish", code: "irish"),
    Category(name: "Island Pub", code: "island_pub"),
    Category(name: "Israeli", code: "israeli"),
    Category(name: "Italian", code: "italian"),
    Category(name: "Japanese", code: "japanese"),
    Category(name: "Jewish", code: "jewish"),
    Category(name: "Kebab", code: "kebab"),
    Category(name: "Korean", code: "korean"),
    Category(name: "Kosher", code: "kosher"),
    Category(name: "Kurdish", code: "kurdish"),
    Category(name: "Laos", code: "laos"),
    Category(name: "Laotian", code: "laotian"),
    Category(name: "Latin American", code: "latin"),
    Category(name: "Live/Raw Food", code: "raw_food"),
    Category(name: "Lyonnais", code: "lyonnais"),
    Category(name: "Malaysian", code: "malaysian"),
    Category(name: "Meatballs", code: "meatballs"),
    Category(name: "Mediterranean", code: "mediterranean"),
    Category(name: "Mexican", code: "mexican"),
    Category(name: "Middle Eastern", code: "mideastern"),
    Category(name: "Milk Bars", code: "milkbars"),
    Category(name: "Modern Australian", code: "modern_australian"),
    Category(name: "Modern European", code: "modern_european"),
    Category(name: "Mongolian", code: "mongolian"),
    Category(name: "Moroccan", code: "moroccan"),
    Category(name: "New Zealand", code: "newzealand"),
    Category(name: "Night Food", code: "nightfood"),
    Category(name: "Norcinerie", code: "norcinerie"),
    Category(name: "Open Sandwiches", code: "opensandwiches"),
    Category(name: "Oriental", code: "oriental"),
    Category(name: "Pakistani", code: "pakistani"),
    Category(name: "Parent Cafes", code: "eltern_cafes"),
    Category(name: "Parma", code: "parma"),
    Category(name: "Persian/Iranian", code: "persian"),
    Category(name: "Peruvian", code: "peruvian"),
    Category(name: "Pita", code: "pita"),
    Category(name: "Pizza", code: "pizza"),
    Category(name: "Polish", code: "polish"),
    Category(name: "Portuguese", code: "portuguese"),
    Category(name: "Potatoes", code: "potatoes"),
    Category(name: "Poutineries", code: "poutineries"),
    Category(name: "Pub Food", code: "pubfood"),
    Category(name: "Rice", code: "riceshop"),
    Category(name: "Romanian", code: "romanian"),
    Category(name: "Rotisserie Chicken", code: "rotisserie_chicken"),
    Category(name: "Rumanian", code: "rumanian"),
    Category(name: "Russian", code: "russian"),
    Category(name: "Salad", code: "salad"),
    Category(name: "Sandwiches", code: "sandwiches"),
    Category(name: "Scandinavian", code: "scandinavian"),
    Category(name: "Scottish", code: "scottish"),
    Category(name: "Seafood", code: "seafood"),
    Category(name: "Serbo Croatian", code: "serbocroatian"),
    Category(name: "Signature Cuisine", code: "signature_cuisine"),
    Category(name: "Singaporean", code: "singaporean"),
    Category(name: "Slovakian", code: "slovakian"),
    Category(name: "Soul Food", code: "soulfood"),
    Category(name: "Soup", code: "soup"),
    Category(name: "Southern", code: "southern"),
    Category(name: "Spanish", code: "spanish"),
    Category(name: "Steakhouses", code: "steak"),
    Category(name: "Sushi Bars", code: "sushi"),
    Category(name: "Swabian", code: "swabian"),
    Category(name: "Swedish", code: "swedish"),
    Category(name: "Swiss Food", code: "swissfood"),
    Category(name: "Tabernas", code: "tabernas"),
    Category(name: "Taiwanese", code: "taiwanese"),
    Category(name: "Tapas Bars", code: "tapas"),
    Category(name: "Tapas/Small Plates", code: "tapasmallplates"),
    Category(name: "Tex-Mex", code: "tex-mex"),
    Category(name: "Thai", code: "thai"),
    Category(name: "Traditional Norwegian", code: "norwegian"),
    Category(name: "Traditional Swedish", code: "traditional_swedish"),
    Category(name: "Trattorie", code: "trattorie"),
    Category(name: "Turkish", code: "turkish"),
    Category(name: "Ukrainian", code: "ukrainian"),
    Category(name: "Uzbek", code: "uzbek"),
    Category(name: "Vegan", code: "vegan"),
    Category(name: "Vegetarian", code: "vegetarian"),
    Category(name: "Venison", code: "venison"),
    Category(name: "Vietnamese", code: "vietnamese"),
    Category(name: "Wok", code: "wok"),
    Category(name: "Wraps", code: "wraps"),
    Category(name: "Yugoslav", code: "yugoslav")
]
